copyright: Copyright &copy;2021-2022, Konnexions GmbH.

edit_uri: ""

extra:
  generator: false
extra_css:
  - assets/pymdownx-extras/extra-b1466b3f51.css
extra_javascript:
  - https://unpkg.com/mermaid@8.13.3/dist/mermaid.min.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - assets/pymdownx-extras/extra-loader-9e2c67b9.js

markdown_extensions:
  - attr_list
  - pymdownx.tilde
  - toc : {
    toc_depth: "1-3"
  }

nav:
  - Home: index.md
  - Application:
      - Requirementes: application_requirements.md
      - Installaion: application_installation.md
      - Configuration: application_configuration.md
      - Operations: application_operations.md
      - Document Language: application_document_language.md
  - Release Documents:
    - Release Notes: release_notes.md
    - Release History: release_history.md
  - Development:
      - Research Notes: developing_research_notes.md
      - System Environment: development_system_environment.md
      - Coding Standards: development_coding_standards.md
      - Code Formatting: development_code_formatting.md
      - Static Code Analysis: development_static_code_analysis.md
      - Documentation:
        - Software Documentation: development_software_documentation.md
        - Line Type Algorithms: development_line_type.md
        - API Documentation: development_api_documentation.md
      - Software Testing: development_software_testing.md
      - Continuous Delivery: development_continuous_delivery.md
      - Environment: development_development_environment.md
      - Version Planning: development_version_planning.md
  - Code of Conduct: code_of_conduct.md
  - Contributing Guide: contributing.md
  - License: license.md

plugins:
  - search
  - awesome-pages
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            heading_level: 3
            paths: [src]
            show_root_heading: false
            show_source: true

repo_url: https://github.com/KonnexionsGmbH/dcr-core/

site_name: DCR-CORE - Document Content Recognition API
site_url: https://www.konnexions.ch/
site_description: Document Content Recognition API
site_author: Konnexions GmbH Team

theme:
  favicon: img/Icon.png
  features:
    - search.highlight
    - search.suggest
  language: en
  logo: img/Logo.png
  name: material
  palette:
    primary: blue
    accent: red
