import pathlib

def check_exists_object(
    is_line_type_headers_footers: bool = ...,
    is_line_type_list_bullet: bool = ...,
    is_line_type_list_number: bool = ...,
    is_line_type_table: bool = ...,
    is_line_type_toc: bool = ...,
    is_setup: bool = ...,
    is_text_parser: bool = ...,
) -> None: ...
def get_full_name(directory_name: pathlib.Path | str | None, file_name: pathlib.Path | str | None) -> str: ...
def get_os_independent_name(name: pathlib.Path | str | None) -> str: ...
def get_stem_name(file_name: pathlib.Path | str | None) -> str: ...
def progress_msg(is_verbose: bool, msg: str) -> None: ...
def progress_msg_core(msg: str) -> None: ...
def terminate_fatal(error_msg: str) -> None: ...
